app/assets/stylesheets/tasks.scss, app/controllers/tasks_controller.rb, app/helpers/tasks_helper.rb, app/models/project.rb, app/models/role.rb, app/models/task.rb, app/models/user.rb, app/views/tasks/destroy.html.erb, app/views/tasks/edit.html.erb, app/views/tasks/index.html.erb, app/views/tasks/newcreate.html.erb, app/views/tasks/show.html.erb, app/views/tasks/update.html.erb, config/routes.rb, db/migrate/20220325202145_create_roles.rb, db/migrate/20220325202809_add_column_user.rb, db/schema.rb, test/controllers/tasks_controller_test.rb, test/fixtures/roles.yml, test/models/role_test.rb
add table role with role_id on Users table initialize controller-task n Validates model
=> finish controller task n add role table

app/models/daysoff.rb, app/models/holiday.rb, db/migrate/20220325205444_create_holidays.rb, db/migrate/20220325205550_create_daysoffs.rb, db/schema.rb, test/fixtures/daysoffs.yml, test/fixtures/holidays.yml, test/models/daysoff_test.rb, test/models/holiday_test.rb
I've add some table (holiday n days_off)
=> add table holiday n days_off with validate

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_general_rules.scss, app/views/layouts/application.html.erb, app/views/shared/_sidebar.html.erb
=> update maitre stage

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_sidebar.html.erb, package.json, yarn.lock
=> change home

app/assets/stylesheets/application.scss, app/assets/stylesheets/dashboard.scss, app/controllers/dashboard_controller.rb, app/helpers/dashboard_helper.rb, app/views/dashboard/index.html.erb, config/routes.rb, test/controllers/dashboard_controller_test.rb
création controller & la route
=> dashboard create

app/assets/config/manifest.js, app/assets/stylesheets/components/_card-task-show.scss, app/assets/stylesheets/components/_card-task.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_sidebar.scss, app/controllers/tasks_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_form-task-edit.html.erb, app/views/shared/_form-task.html.erb, app/views/shared/_sidebar.html.erb, app/views/tasks/destroy.html.erb, app/views/tasks/edit.html.erb, app/views/tasks/index.html.erb, app/views/tasks/new.html.erb, app/views/tasks/newcreate.html.erb, app/views/tasks/show.html.erb, app/views/tasks/update.html.erb
add crud task whit some design
=> initialize crud task

app/assets/config/manifest.js, app/assets/stylesheets/components/_btn-color.scss, app/assets/stylesheets/components/_card-task-show.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_sidebar.scss, app/controllers/projects_controller.rb, app/controllers/tasks_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_sidebar.html.erb, app/views/tasks/index.html.erb
change sidebar with some button
=> change sidebar with button

app/controllers/tasks_controller.rb, app/views/projects/show.html.erb
=> first debug

app/assets/stylesheets/components/_btn-color.scss, app/controllers/tasks_controller.rb, app/models/task.rb, app/views/shared/_form-task-edit.html.erb, app/views/shared/_form-task.html.erb, app/views/shared/_sidebar.html.erb, app/views/tasks/index.html.erb
ajout des liens sans ajax pour l'instant et correction beug create /update
=> add link debuf create/update task

app/views/shared/_form-task.html.erb
=> maj formulaire pour les assign

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/teams.scss, app/controllers/teams_controller.rb, app/helpers/teams_helper.rb, app/views/shared/_sidebar.html.erb, app/views/teams/index.html.erb, config/routes.rb, test/controllers/teams_controller_test.rb
create controller teams avec sa vue et sa routes
=> add controller teams n route with views

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/teams.scss, app/views/shared/_navbar.html.erb, app/views/teams/index.html.erb, config/routes.rb
=> maj teampages

app/controllers/tasks_controller.rb, app/models/task.rb
ajout du calcule tjm dans le model
=> add calcultor tjm on taskmodel

app/assets/stylesheets/components/_index.scss, app/views/shared/_sidebar.html.erb
=> little update make

app/assets/stylesheets/components/_form.scss, app/views/devise/sessions/new.html.erb
=> finish login placement

app/views/dashboard/index.html.erb
update fill project on calendar
=> finish info project dasboard

app/assets/stylesheets/components/_card-task-show.scss, db/seeds.rb
=> changer seed n show tasks

app/models/task.rb, app/views/projects/index.html.erb, app/views/shared/_form-task.html.erb
=> update faite create wroking

app/models/task.rb, db/migrate/20220404162741_change_column_status_to_task.rb, db/schema.rb
change default on statut = 'to do'
=> change column to status

app/assets/stylesheets/components/_card-project.scss, app/models/daysoff.rb, app/models/user.rb, app/views/projects/index.html.erb, db/migrate/20220401203323_add_user_to_days_offs.rb, db/schema.rb
User column added to daysoff
daysoff model belongs_to users
user model has_many daysoffs
=> Project front

app/views/projects/new.html.erb, app/views/projects/show.html.erb
=> french-translation-pages

app/assets/stylesheets/components/_card-project.scss, app/assets/stylesheets/components/_card-task.scss, app/assets/stylesheets/components/_sidebar.scss, app/views/projects/index.html.erb, app/views/shared/_sidebar.html.erb, app/views/tasks/index.html.erb, app/views/tasks/user_tasks.html.erb, db/schema.rb
=> add sidebar responsible with burger

app/views/projects/edit.html.erb
Formulaire d'éditer un projet corrigé
=> project-form-update

app/models/task.rb, app/models/user.rb, app/views/shared/_form-project.html.erb, app/views/tasks/index.html.erb, app/views/tasks/show.html.erb, config/routes.rb
=> little update

app/assets/stylesheets/roles.scss, app/controllers/roles_controller.rb, app/helpers/roles_helper.rb, app/views/layouts/application.html.erb, app/views/roles/create.html.erb, app/views/roles/index.html.erb, app/views/roles/new.html.erb, app/views/shared/_sidebar.html.erb, app/views/tasks/index.html.erb, config/routes.rb, test/controllers/roles_controller_test.rb
ajout création role et de role dans la sidebar avec possibilité de créer et supprimer
=> ajout créer un role

app/views/shared/_form-task.html.erb
ajoute du choix 1 a 10 formulaire de tâche
=> ajout liste de &1 a 10 formulaire task

app/controllers/tasks_controller.rb, app/views/projects/show.html.erb, app/views/tasks/user_tasks.html.erb
change index task project = project
=> change project index
